# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hostel_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import Hostel_backend

class Ui_Form(QtWidgets.QWidget):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 612)
        self.Management_TabWidget = QtWidgets.QTabWidget(Form)
        self.Management_TabWidget.setGeometry(QtCore.QRect(11, 20, 741, 521))
        self.Management_TabWidget.setObjectName("Management_TabWidget")
        self.student_tab = QtWidgets.QWidget()
        self.student_tab.setObjectName("student_tab")
        self.student_input_frame = QtWidgets.QFrame(self.student_tab)
        self.student_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.student_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_input_frame.setObjectName("student_input_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.student_input_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 0, 221, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.student_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.student_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.student_line_verticalLayout_1.setObjectName("student_line_verticalLayout_1")
        self.student_reg_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.student_reg_line.setObjectName("student_reg_line")
        self.student_line_verticalLayout_1.addWidget(self.student_reg_line)
        self.student_name_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.student_name_line.setObjectName("student_name_line")
        self.student_line_verticalLayout_1.addWidget(self.student_name_line)
        self.student_father_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.student_father_line.setObjectName("student_father_line")
        self.student_line_verticalLayout_1.addWidget(self.student_father_line)
        self.student_room_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.student_room_line.setObjectName("student_room_line")
        self.student_line_verticalLayout_1.addWidget(self.student_room_line)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.student_input_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 121, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.student_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.student_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.student_label_verticalLayout_1.setObjectName("student_label_verticalLayout_1")
        self.student_reg_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.student_reg_label.setObjectName("student_reg_label")
        self.student_label_verticalLayout_1.addWidget(self.student_reg_label, 0, QtCore.Qt.AlignRight)
        self.student_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.student_name_label.setObjectName("student_name_label")
        self.student_label_verticalLayout_1.addWidget(self.student_name_label, 0, QtCore.Qt.AlignRight)
        self.student_father_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.student_father_label.setObjectName("student_father_label")
        self.student_label_verticalLayout_1.addWidget(self.student_father_label, 0, QtCore.Qt.AlignRight)
        self.student_room_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.student_room_label.setObjectName("student_room_label")
        self.student_label_verticalLayout_1.addWidget(self.student_room_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.student_input_frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(370, 0, 101, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.student_label_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.student_label_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.student_label_verticalLayout_2.setObjectName("student_label_verticalLayout_2")
        self.student_contact_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.student_contact_label.setObjectName("student_contact_label")
        self.student_label_verticalLayout_2.addWidget(self.student_contact_label, 0, QtCore.Qt.AlignRight)
        self.student_dob_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.student_dob_label.setObjectName("student_dob_label")
        self.student_label_verticalLayout_2.addWidget(self.student_dob_label, 0, QtCore.Qt.AlignRight)
        self.student_hostel_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.student_hostel_label.setObjectName("student_hostel_label")
        self.student_label_verticalLayout_2.addWidget(self.student_hostel_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.student_input_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(480, 0, 221, 82))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.student_line_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.student_line_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.student_line_verticalLayout_2.setObjectName("student_line_verticalLayout_2")
        self.student_contact_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.student_contact_line.setObjectName("student_contact_line")
        self.student_line_verticalLayout_2.addWidget(self.student_contact_line)
        self.student_dob_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.student_dob_line.setObjectName("student_dob_line")
        self.student_line_verticalLayout_2.addWidget(self.student_dob_line)
        self.student_hostel_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.student_hostel_line.setObjectName("student_hostel_line")
        self.student_line_verticalLayout_2.addWidget(self.student_hostel_line)
        self.student_table_frame = QtWidgets.QFrame(self.student_tab)
        self.student_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.student_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_table_frame.setObjectName("student_table_frame")
        self.student_table = QtWidgets.QTableWidget(self.student_table_frame)
        self.student_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.student_table.setObjectName("student_table")
        self.student_table.setColumnCount(7)
        self.student_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_table.setHorizontalHeaderItem(6, item)
        self.Management_TabWidget.addTab(self.student_tab, "")
        self.hostel_tab = QtWidgets.QWidget()
        self.hostel_tab.setObjectName("hostel_tab")
        self.hostel_input_frame = QtWidgets.QFrame(self.hostel_tab)
        self.hostel_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.hostel_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hostel_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hostel_input_frame.setObjectName("hostel_input_frame")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.hostel_input_frame)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(140, 0, 221, 111))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.hostel_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.hostel_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.hostel_line_verticalLayout_1.setObjectName("hostel_line_verticalLayout_1")
        self.hostel_hostel_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.hostel_hostel_line.setObjectName("hostel_hostel_line")
        self.hostel_line_verticalLayout_1.addWidget(self.hostel_hostel_line)
        self.hostel_rooms_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.hostel_rooms_line.setObjectName("hostel_rooms_line")
        self.hostel_line_verticalLayout_1.addWidget(self.hostel_rooms_line)
        self.hostel_students_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.hostel_students_line.setObjectName("hostel_students_line")
        self.hostel_line_verticalLayout_1.addWidget(self.hostel_students_line)
        self.hostel_expenses_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.hostel_expenses_line.setObjectName("hostel_expenses_line")
        self.hostel_line_verticalLayout_1.addWidget(self.hostel_expenses_line)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.hostel_input_frame)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 0, 121, 111))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.hostel_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.hostel_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.hostel_label_verticalLayout_1.setObjectName("hostel_label_verticalLayout_1")
        self.hostel_hostel_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.hostel_hostel_label.setObjectName("hostel_hostel_label")
        self.hostel_label_verticalLayout_1.addWidget(self.hostel_hostel_label, 0, QtCore.Qt.AlignRight)
        self.hostel_rooms_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.hostel_rooms_label.setObjectName("hostel_rooms_label")
        self.hostel_label_verticalLayout_1.addWidget(self.hostel_rooms_label, 0, QtCore.Qt.AlignRight)
        self.hostel_students_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.hostel_students_label.setObjectName("hostel_students_label")
        self.hostel_label_verticalLayout_1.addWidget(self.hostel_students_label, 0, QtCore.Qt.AlignRight)
        self.hostel_expenses_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.hostel_expenses_label.setObjectName("hostel_expenses_label")
        self.hostel_label_verticalLayout_1.addWidget(self.hostel_expenses_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.hostel_input_frame)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(370, 0, 101, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.hostel_label_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.hostel_label_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.hostel_label_verticalLayout_2.setObjectName("hostel_label_verticalLayout_2")
        self.hostel_location_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.hostel_location_label.setObjectName("hostel_location_label")
        self.hostel_label_verticalLayout_2.addWidget(self.hostel_location_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.hostel_input_frame)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(480, 0, 221, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.hostel_line_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.hostel_line_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.hostel_line_verticalLayout_2.setObjectName("hostel_line_verticalLayout_2")
        self.hostel_location_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        self.hostel_location_line.setObjectName("hostel_location_line")
        self.hostel_line_verticalLayout_2.addWidget(self.hostel_location_line)
        self.hostel_table_frame = QtWidgets.QFrame(self.hostel_tab)
        self.hostel_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.hostel_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hostel_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hostel_table_frame.setObjectName("hostel_table_frame")
        self.hostel_table = QtWidgets.QTableWidget(self.hostel_table_frame)
        self.hostel_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.hostel_table.setObjectName("hostel_table")
        self.hostel_table.setColumnCount(5)
        self.hostel_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hostel_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostel_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostel_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostel_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostel_table.setHorizontalHeaderItem(4, item)
        self.Management_TabWidget.addTab(self.hostel_tab, "")
        self.room_tab = QtWidgets.QWidget()
        self.room_tab.setObjectName("room_tab")
        self.room_input_frame = QtWidgets.QFrame(self.room_tab)
        self.room_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.room_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.room_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.room_input_frame.setObjectName("room_input_frame")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.room_input_frame)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(140, 0, 221, 111))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.room_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.room_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.room_line_verticalLayout_1.setObjectName("room_line_verticalLayout_1")
        self.room_room_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.room_room_line.setObjectName("room_room_line")
        self.room_line_verticalLayout_1.addWidget(self.room_room_line)
        self.room_capacity_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.room_capacity_line.setObjectName("room_capacity_line")
        self.room_line_verticalLayout_1.addWidget(self.room_capacity_line)
        self.room_hostel_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.room_hostel_line.setObjectName("room_hostel_line")
        self.room_line_verticalLayout_1.addWidget(self.room_hostel_line)
        self.room_type_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.room_type_line.setObjectName("room_type_line")
        self.room_line_verticalLayout_1.addWidget(self.room_type_line)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.room_input_frame)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 0, 121, 111))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.room_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.room_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.room_label_verticalLayout_1.setObjectName("room_label_verticalLayout_1")
        self.room_room_label = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.room_room_label.setObjectName("room_room_label")
        self.room_label_verticalLayout_1.addWidget(self.room_room_label, 0, QtCore.Qt.AlignRight)
        self.room_capacity_label = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.room_capacity_label.setObjectName("room_capacity_label")
        self.room_label_verticalLayout_1.addWidget(self.room_capacity_label, 0, QtCore.Qt.AlignRight)
        self.room_hostel_label = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.room_hostel_label.setObjectName("room_hostel_label")
        self.room_label_verticalLayout_1.addWidget(self.room_hostel_label, 0, QtCore.Qt.AlignRight)
        self.room_type_label = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.room_type_label.setObjectName("room_type_label")
        self.room_label_verticalLayout_1.addWidget(self.room_type_label, 0, QtCore.Qt.AlignRight)
        self.room_table_frame = QtWidgets.QFrame(self.room_tab)
        self.room_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.room_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.room_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.room_table_frame.setObjectName("room_table_frame")
        self.room_table = QtWidgets.QTableWidget(self.room_table_frame)
        self.room_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.room_table.setObjectName("room_table")
        self.room_table.setColumnCount(4)
        self.room_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(3, item)
        self.Management_TabWidget.addTab(self.room_tab, "")
        self.staff_tab = QtWidgets.QWidget()
        self.staff_tab.setObjectName("staff_tab")
        self.staff_input_frame = QtWidgets.QFrame(self.staff_tab)
        self.staff_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.staff_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staff_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staff_input_frame.setObjectName("staff_input_frame")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.staff_input_frame)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(140, 0, 221, 111))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.staff_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.staff_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.staff_line_verticalLayout_1.setObjectName("staff_line_verticalLayout_1")
        self.staff_emp_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.staff_emp_line.setObjectName("staff_emp_line")
        self.staff_line_verticalLayout_1.addWidget(self.staff_emp_line)
        self.staff_name_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.staff_name_line.setObjectName("staff_name_line")
        self.staff_line_verticalLayout_1.addWidget(self.staff_name_line)
        self.staff_hostel_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.staff_hostel_line.setObjectName("staff_hostel_line")
        self.staff_line_verticalLayout_1.addWidget(self.staff_hostel_line)
        self.staff_salary_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.staff_salary_line.setObjectName("staff_salary_line")
        self.staff_line_verticalLayout_1.addWidget(self.staff_salary_line)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.staff_input_frame)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(10, 0, 121, 111))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.staff_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.staff_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.staff_label_verticalLayout_1.setObjectName("staff_label_verticalLayout_1")
        self.staff_emp_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.staff_emp_label.setObjectName("staff_emp_label")
        self.staff_label_verticalLayout_1.addWidget(self.staff_emp_label, 0, QtCore.Qt.AlignRight)
        self.staff_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.staff_name_label.setObjectName("staff_name_label")
        self.staff_label_verticalLayout_1.addWidget(self.staff_name_label, 0, QtCore.Qt.AlignRight)
        self.staff_hostel_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.staff_hostel_label.setObjectName("staff_hostel_label")
        self.staff_label_verticalLayout_1.addWidget(self.staff_hostel_label, 0, QtCore.Qt.AlignRight)
        self.staff_salary_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.staff_salary_label.setObjectName("staff_salary_label")
        self.staff_label_verticalLayout_1.addWidget(self.staff_salary_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.staff_input_frame)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(370, 0, 101, 111))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.staff_label_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.staff_label_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.staff_label_verticalLayout_2.setObjectName("staff_label_verticalLayout_2")
        self.staff_contact_label = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.staff_contact_label.setObjectName("staff_contact_label")
        self.staff_label_verticalLayout_2.addWidget(self.staff_contact_label, 0, QtCore.Qt.AlignRight)
        self.staff_street_label = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.staff_street_label.setObjectName("staff_street_label")
        self.staff_label_verticalLayout_2.addWidget(self.staff_street_label, 0, QtCore.Qt.AlignRight)
        self.staff_state_label = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.staff_state_label.setObjectName("staff_state_label")
        self.staff_label_verticalLayout_2.addWidget(self.staff_state_label, 0, QtCore.Qt.AlignRight)
        self.staff_pin_label = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.staff_pin_label.setObjectName("staff_pin_label")
        self.staff_label_verticalLayout_2.addWidget(self.staff_pin_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.staff_input_frame)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(480, 0, 221, 111))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.staff_line_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.staff_line_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.staff_line_verticalLayout_2.setObjectName("staff_line_verticalLayout_2")
        self.staff_contact_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.staff_contact_line.setObjectName("staff_contact_line")
        self.staff_line_verticalLayout_2.addWidget(self.staff_contact_line)
        self.staff_street_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.staff_street_line.setObjectName("staff_street_line")
        self.staff_line_verticalLayout_2.addWidget(self.staff_street_line)
        self.staff_state_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.staff_state_line.setObjectName("staff_state_line")
        self.staff_line_verticalLayout_2.addWidget(self.staff_state_line)
        self.staff_pin_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.staff_pin_line.setObjectName("staff_pin_line")
        self.staff_line_verticalLayout_2.addWidget(self.staff_pin_line)
        self.staff_table_frame = QtWidgets.QFrame(self.staff_tab)
        self.staff_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.staff_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staff_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staff_table_frame.setObjectName("staff_table_frame")
        self.staff_table = QtWidgets.QTableWidget(self.staff_table_frame)
        self.staff_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.staff_table.setObjectName("staff_table")
        self.staff_table.setColumnCount(8)
        self.staff_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_table.setHorizontalHeaderItem(7, item)
        self.Management_TabWidget.addTab(self.staff_tab, "")
        self.mess_tab = QtWidgets.QWidget()
        self.mess_tab.setObjectName("mess_tab")
        self.mess_table_frame = QtWidgets.QFrame(self.mess_tab)
        self.mess_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.mess_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mess_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mess_table_frame.setObjectName("mess_table_frame")
        self.mess_table = QtWidgets.QTableWidget(self.mess_table_frame)
        self.mess_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.mess_table.setObjectName("mess_table")
        self.mess_table.setColumnCount(6)
        self.mess_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mess_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mess_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mess_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mess_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mess_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.mess_table.setHorizontalHeaderItem(5, item)
        self.mess_input_frame = QtWidgets.QFrame(self.mess_tab)
        self.mess_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.mess_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mess_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mess_input_frame.setObjectName("mess_input_frame")
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.mess_input_frame)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(140, 0, 221, 111))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.mess_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.mess_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.mess_line_verticalLayout_1.setObjectName("mess_line_verticalLayout_1")
        self.mess_incharge_line_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.mess_incharge_line_2.setObjectName("mess_incharge_line_2")
        self.mess_line_verticalLayout_1.addWidget(self.mess_incharge_line_2)
        self.mess_expenses_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.mess_expenses_line.setObjectName("mess_expenses_line")
        self.mess_line_verticalLayout_1.addWidget(self.mess_expenses_line)
        self.mess_bf_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.mess_bf_line.setObjectName("mess_bf_line")
        self.mess_line_verticalLayout_1.addWidget(self.mess_bf_line)
        self.mess_ln_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.mess_ln_line.setObjectName("mess_ln_line")
        self.mess_line_verticalLayout_1.addWidget(self.mess_ln_line)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.mess_input_frame)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 0, 121, 111))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.mess_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.mess_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.mess_label_verticalLayout_1.setObjectName("mess_label_verticalLayout_1")
        self.mess_incharge_label = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.mess_incharge_label.setObjectName("mess_incharge_label")
        self.mess_label_verticalLayout_1.addWidget(self.mess_incharge_label, 0, QtCore.Qt.AlignRight)
        self.mess_expenses_label = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.mess_expenses_label.setObjectName("mess_expenses_label")
        self.mess_label_verticalLayout_1.addWidget(self.mess_expenses_label, 0, QtCore.Qt.AlignRight)
        self.mess_bf_label = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.mess_bf_label.setObjectName("mess_bf_label")
        self.mess_label_verticalLayout_1.addWidget(self.mess_bf_label, 0, QtCore.Qt.AlignRight)
        self.mess_ln_label = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.mess_ln_label.setObjectName("mess_ln_label")
        self.mess_label_verticalLayout_1.addWidget(self.mess_ln_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.mess_input_frame)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(370, 0, 101, 51))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.mess_label_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.mess_label_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.mess_label_verticalLayout_2.setObjectName("mess_label_verticalLayout_2")
        self.mess_dn_label = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.mess_dn_label.setObjectName("mess_dn_label")
        self.mess_label_verticalLayout_2.addWidget(self.mess_dn_label, 0, QtCore.Qt.AlignRight)
        self.mess_type_label = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.mess_type_label.setObjectName("mess_type_label")
        self.mess_label_verticalLayout_2.addWidget(self.mess_type_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.mess_input_frame)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(480, 0, 221, 53))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.mess_line_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.mess_line_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.mess_line_verticalLayout_2.setObjectName("mess_line_verticalLayout_2")
        self.mess_dn_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.mess_dn_line.setObjectName("mess_dn_line")
        self.mess_line_verticalLayout_2.addWidget(self.mess_dn_line)
        self.mess_type_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_19)
        self.mess_type_line.setObjectName("mess_type_line")
        self.mess_line_verticalLayout_2.addWidget(self.mess_type_line)
        self.Management_TabWidget.addTab(self.mess_tab, "")
        self.fee_tab = QtWidgets.QWidget()
        self.fee_tab.setObjectName("fee_tab")
        self.fee_input_frame = QtWidgets.QFrame(self.fee_tab)
        self.fee_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.fee_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fee_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fee_input_frame.setObjectName("fee_input_frame")
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.fee_input_frame)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(140, 0, 221, 82))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.fee_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.fee_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.fee_line_verticalLayout_1.setObjectName("fee_line_verticalLayout_1")
        self.fee_status_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        self.fee_status_line.setObjectName("fee_status_line")
        self.fee_line_verticalLayout_1.addWidget(self.fee_status_line)
        self.fee_amt_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        self.fee_amt_line.setObjectName("fee_amt_line")
        self.fee_line_verticalLayout_1.addWidget(self.fee_amt_line)
        self.fee_student_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        self.fee_student_line.setObjectName("fee_student_line")
        self.fee_line_verticalLayout_1.addWidget(self.fee_student_line)
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.fee_input_frame)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(10, 0, 121, 81))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.fee_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.fee_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.fee_label_verticalLayout_1.setObjectName("fee_label_verticalLayout_1")
        self.fee_status_label = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        self.fee_status_label.setObjectName("fee_status_label")
        self.fee_label_verticalLayout_1.addWidget(self.fee_status_label, 0, QtCore.Qt.AlignRight)
        self.fee_amt_label = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        self.fee_amt_label.setObjectName("fee_amt_label")
        self.fee_label_verticalLayout_1.addWidget(self.fee_amt_label, 0, QtCore.Qt.AlignRight)
        self.fee_student_label = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        self.fee_student_label.setObjectName("fee_student_label")
        self.fee_label_verticalLayout_1.addWidget(self.fee_student_label, 0, QtCore.Qt.AlignRight)
        self.fee_table_frame = QtWidgets.QFrame(self.fee_tab)
        self.fee_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.fee_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fee_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fee_table_frame.setObjectName("fee_table_frame")
        self.fee_table = QtWidgets.QTableWidget(self.fee_table_frame)
        self.fee_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.fee_table.setObjectName("fee_table")
        self.fee_table.setColumnCount(3)
        self.fee_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fee_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fee_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fee_table.setHorizontalHeaderItem(2, item)
        self.Management_TabWidget.addTab(self.fee_tab, "")
        self.furniture_tab = QtWidgets.QWidget()
        self.furniture_tab.setObjectName("furniture_tab")
        self.furniture_input_frame = QtWidgets.QFrame(self.furniture_tab)
        self.furniture_input_frame.setGeometry(QtCore.QRect(10, 10, 711, 111))
        self.furniture_input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.furniture_input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.furniture_input_frame.setObjectName("furniture_input_frame")
        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.furniture_input_frame)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(140, 0, 221, 82))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.furniture_line_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.furniture_line_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.furniture_line_verticalLayout_1.setObjectName("furniture_line_verticalLayout_1")
        self.furniture_id_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.furniture_id_line.setObjectName("furniture_id_line")
        self.furniture_line_verticalLayout_1.addWidget(self.furniture_id_line)
        self.furniture_type_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.furniture_type_line.setObjectName("furniture_type_line")
        self.furniture_line_verticalLayout_1.addWidget(self.furniture_type_line)
        self.furniture_room_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_22)
        self.furniture_room_line.setObjectName("furniture_room_line")
        self.furniture_line_verticalLayout_1.addWidget(self.furniture_room_line)
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.furniture_input_frame)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(10, 0, 121, 81))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.furniture_label_verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.furniture_label_verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.furniture_label_verticalLayout_1.setObjectName("furniture_label_verticalLayout_1")
        self.furniture_id_label = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.furniture_id_label.setObjectName("furniture_id_label")
        self.furniture_label_verticalLayout_1.addWidget(self.furniture_id_label, 0, QtCore.Qt.AlignRight)
        self.furniture_type_label = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.furniture_type_label.setObjectName("furniture_type_label")
        self.furniture_label_verticalLayout_1.addWidget(self.furniture_type_label, 0, QtCore.Qt.AlignRight)
        self.furniture_room_label = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.furniture_room_label.setObjectName("furniture_room_label")
        self.furniture_label_verticalLayout_1.addWidget(self.furniture_room_label, 0, QtCore.Qt.AlignRight)
        self.furniture_table_frame = QtWidgets.QFrame(self.furniture_tab)
        self.furniture_table_frame.setGeometry(QtCore.QRect(10, 130, 711, 351))
        self.furniture_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.furniture_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.furniture_table_frame.setObjectName("furniture_table_frame")
        self.furniture_table = QtWidgets.QTableWidget(self.furniture_table_frame)
        self.furniture_table.setGeometry(QtCore.QRect(10, 10, 691, 331))
        self.furniture_table.setObjectName("furniture_table")
        self.furniture_table.setColumnCount(3)
        self.furniture_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.furniture_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.furniture_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.furniture_table.setHorizontalHeaderItem(2, item)
        self.Management_TabWidget.addTab(self.furniture_tab, "")
        self.function_buttons_frame = QtWidgets.QFrame(Form)
        self.function_buttons_frame.setGeometry(QtCore.QRect(11, 547, 741, 61))
        self.function_buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.function_buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.function_buttons_frame.setObjectName("function_buttons_frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.function_buttons_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.function_buttons_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.function_buttons_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.function_buttons_horizontalLayout.setObjectName("function_buttons_horizontalLayout")
        self.view_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.view_btn.setObjectName("view_btn")
        self.function_buttons_horizontalLayout.addWidget(self.view_btn)
        self.search_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.search_btn.setObjectName("search_btn")
        self.function_buttons_horizontalLayout.addWidget(self.search_btn)
        self.add_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.function_buttons_horizontalLayout.addWidget(self.add_btn)
        self.update_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.update_btn.setObjectName("update_btn")
        self.function_buttons_horizontalLayout.addWidget(self.update_btn)
        self.delete_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete_btn.setObjectName("delete_btn")
        self.function_buttons_horizontalLayout.addWidget(self.delete_btn)


        # add all the functinality here
        self.view_btn.clicked.connect(self.view_command)
        self.add_btn.clicked.connect(self.insert_command)
        self.search_btn.clicked.connect(self.search_command)
        self.delete_btn.clicked.connect(self.delete_command)
        self.update_btn.clicked.connect(self.update_command)


        self.retranslateUi(Form)
        self.Management_TabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.student_reg_label.setText(_translate("Form", "Registration number"))
        self.student_name_label.setText(_translate("Form", "Name"))
        self.student_father_label.setText(_translate("Form", "Father\'s name"))
        self.student_room_label.setText(_translate("Form", "Room number"))
        self.student_contact_label.setText(_translate("Form", "Contact number"))
        self.student_dob_label.setText(_translate("Form", "Date of Birth"))
        self.student_hostel_label.setText(_translate("Form", "Hostel Building"))
        item = self.student_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "regno"))
        item = self.student_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "name"))
        item = self.student_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "father_name"))
        item = self.student_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "room_no"))
        item = self.student_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "contact_no"))
        item = self.student_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "dob"))
        item = self.student_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "hostel_building"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.student_tab), _translate("Form", "Student"))
        self.hostel_hostel_label.setText(_translate("Form", "Hostel Building"))
        self.hostel_rooms_label.setText(_translate("Form", "Number of Rooms"))
        self.hostel_students_label.setText(_translate("Form", "Number of Students"))
        self.hostel_expenses_label.setText(_translate("Form", "Expenses"))
        self.hostel_location_label.setText(_translate("Form", "Location"))
        item = self.hostel_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "hostel_building"))
        item = self.hostel_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "no_of_rooms"))
        item = self.hostel_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "no_of_students"))
        item = self.hostel_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "expenses"))
        item = self.hostel_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "location"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.hostel_tab), _translate("Form", "Hostel"))
        self.room_room_label.setText(_translate("Form", "Room number"))
        self.room_capacity_label.setText(_translate("Form", "Capacity"))
        self.room_hostel_label.setText(_translate("Form", "Hostel Building"))
        self.room_type_label.setText(_translate("Form", "room_type"))
        item = self.room_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "room_no"))
        item = self.room_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "capacity"))
        item = self.room_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "hostel_building"))
        item = self.room_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "room_type"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.room_tab), _translate("Form", "Room"))
        self.staff_emp_label.setText(_translate("Form", "Employee ID"))
        self.staff_name_label.setText(_translate("Form", "Name"))
        self.staff_hostel_label.setText(_translate("Form", "Hostel Building"))
        self.staff_salary_label.setText(_translate("Form", "Salary"))
        self.staff_contact_label.setText(_translate("Form", "Contact number"))
        self.staff_street_label.setText(_translate("Form", "Street"))
        self.staff_state_label.setText(_translate("Form", "State"))
        self.staff_pin_label.setText(_translate("Form", "Pincode"))
        item = self.staff_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "emp_ID"))
        item = self.staff_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "name"))
        item = self.staff_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "hostel_building"))
        item = self.staff_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "salary"))
        item = self.staff_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "contact_no"))
        item = self.staff_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "street"))
        item = self.staff_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "state"))
        item = self.staff_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "pincode"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.staff_tab), _translate("Form", "Staff"))
        item = self.mess_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "incharge"))
        item = self.mess_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "expenses"))
        item = self.mess_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "bf_timings"))
        item = self.mess_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ln_timings"))
        item = self.mess_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "dn_timings"))
        item = self.mess_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "mess_type"))
        self.mess_incharge_label.setText(_translate("Form", "Incharge"))
        self.mess_expenses_label.setText(_translate("Form", "Expenses"))
        self.mess_bf_label.setText(_translate("Form", "Breakfast timings"))
        self.mess_ln_label.setText(_translate("Form", "Lunch timings"))
        self.mess_dn_label.setText(_translate("Form", "Dinner timings"))
        self.mess_type_label.setText(_translate("Form", "Mess type"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.mess_tab), _translate("Form", "Mess"))
        self.fee_status_label.setText(_translate("Form", "Fee Status"))
        self.fee_amt_label.setText(_translate("Form", "Fee amount"))
        self.fee_student_label.setText(_translate("Form", "Student ID"))
        item = self.fee_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "fee_status"))
        item = self.fee_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "fee_amount"))
        item = self.fee_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "student_ID"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.fee_tab), _translate("Form", "Fee"))
        self.furniture_id_label.setText(_translate("Form", "Furniture ID"))
        self.furniture_type_label.setText(_translate("Form", "Furniture type"))
        self.furniture_room_label.setText(_translate("Form", "Room number"))
        item = self.furniture_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "furniture_ID"))
        item = self.furniture_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "furniture_type"))
        item = self.furniture_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "room_no"))
        self.Management_TabWidget.setTabText(self.Management_TabWidget.indexOf(self.furniture_tab), _translate("Form", "Furniture"))
        self.view_btn.setText(_translate("Form", "View All"))
        self.search_btn.setText(_translate("Form", "Search"))
        self.add_btn.setText(_translate("Form", "Add"))
        self.update_btn.setText(_translate("Form", "Update Selected"))
        self.delete_btn.setText(_translate("Form", "Delete Selected"))

        

    def current_tab_name(self, index):
        ''' takes the current tab index and returns the tab name '''
        if (index == 0):
            return "student_tab"
        elif (index == 1):
            return "hostel_tab"
        elif (index == 2):
            return "room_tab"
        elif (index == 3):
            return "staff_tab"
        elif (index == 4):
            return "mess_tab"
        elif (index == 5):
            return "fee_tab"
        elif (index == 6):
            return "furniture_tab"
        else :
            pass

    def current_table_name(self, index):
        ''' takes the current tab index and returns the table in that tab '''
        if (index == 0):
            return self.student_table
        elif (index == 1):
            return self.hostel_table
        elif (index == 2):
            return self.room_table
        elif (index == 3):
            return self.staff_table
        elif (index == 4):
            return self.mess_table
        elif (index == 5):
            return self.fee_table
        elif (index == 6):
            return self.furniture_table
        else :
            pass        

    def current_tab_layouts(self, index):
        if (index == 0):
            return [self.student_line_verticalLayout_1,self.student_line_verticalLayout_2]
        elif (index == 1):
            return [self.hostel_line_verticalLayout_1, self.hostel_line_verticalLayout_2]
        elif (index == 2):
            return [self.room_line_verticalLayout_1]
        elif (index == 3):
            return [self.staff_line_verticalLayout_1, self.staff_line_verticalLayout_2]
        elif (index == 4):
            return [self.mess_line_verticalLayout_1, self.mess_line_verticalLayout_2]
        elif (index == 5):
            return [self.fee_line_verticalLayout_1]
        elif (index == 6):
            return [self.furniture_line_verticalLayout_1]
        else :
            pass        



    def layout_widgets(self,layout):
        return (layout.itemAt(i) for i in range(layout.count()))


    #for w in layout_widgets(layout):
        #doSomething(w)




    def view_command(self):
        current_tindex = self.Management_TabWidget.currentIndex()
        current_tname = self.current_tab_name(current_tindex)
        current_table = self.current_table_name(current_tindex)
        # instead of displaying the rows in the command line, display in table widget
        dataframe = Hostel_backend.view(current_tname)

        def fill_table(table_name):
            ''' display the values of the table in the table widget '''
            table_name.setRowCount(0)
            for row_number, row_data in enumerate(dataframe):
                table_name.insertRow(row_number)
                for column_number, datapoint in enumerate(row_data):
                    table_name.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(datapoint)))

        fill_table(current_table)


    def insert_command(self):
        #print(self.student_reg_line.text())
        current_tindex = self.Management_TabWidget.currentIndex()
        current_tname = self.current_tab_name(current_tindex)
        
        # getting the text from each of the lineEdit widgets
        def get_lineEdit_inputs(tindex):
            a = []
            for layout in self.current_tab_layouts(tindex):
                for w in self.layout_widgets(layout):
                    a.append(w.widget().text())
            return a

        arguments = get_lineEdit_inputs(current_tindex)
        Hostel_backend.insert(current_tname, *arguments)


    def search_command(self):
        current_tindex = self.Management_TabWidget.currentIndex()
        current_tname = self.current_tab_name(current_tindex)
        current_table = self.current_table_name(current_tindex)
        
        def get_lineEdit_inputs(tindex):
            a = []
            for layout in self.current_tab_layouts(tindex):
                for w in self.layout_widgets(layout):
                    a.append(w.widget().text())
            return a

        arguments = get_lineEdit_inputs(current_tindex)

        
        headercount = current_table.columnCount() 
        keys = [current_table.horizontalHeaderItem(i).text() for i in range(headercount)]

        kw = dict(zip(keys, arguments))
        new_kw = dict([[k,v] for k,v in kw.items() if v != ''])
        dataframe = Hostel_backend.search(current_tname, **new_kw)

        # self.student_table.setHorizontalHeaderItem(0, item)
        def fill_table(table_name):
            ''' display the values of the table in the table widget '''
            table_name.setRowCount(0)
            for row_number, row_data in enumerate(dataframe):
                table_name.insertRow(row_number)
                for column_number, datapoint in enumerate(row_data):
                    table_name.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(datapoint)))

        fill_table(current_table)
        #print(self.student_table.horizontalHeaderItem(0).text())


    def delete_command(self):
        # to make the values of selected row in table widget be displayed on the lineEdit
        # ???

        current_tindex = self.Management_TabWidget.currentIndex()
        current_tname = self.current_tab_name(current_tindex)
        current_table = self.current_table_name(current_tindex)

        # to get the values of the selected row of table widget
        headercount = current_table.columnCount()
        arguments = [current_table.item(current_table.currentRow(),i).text() for i in range(headercount)]

        keys = [current_table.horizontalHeaderItem(i).text() for i in range(headercount)]
        kw = dict(zip(keys, arguments))

        Hostel_backend.delete(current_tname, **kw)
    
    def update_command(self):
        current_tindex = self.Management_TabWidget.currentIndex()
        current_tname = self.current_tab_name(current_tindex)
        current_table = self.current_table_name(current_tindex)        
        
        def get_lineEdit_inputs(tindex):
            a = []
            for layout in self.current_tab_layouts(tindex):
                for w in self.layout_widgets(layout):
                    a.append(w.widget().text())
            return a

        headercount = current_table.columnCount()
        kwargs_arguments = get_lineEdit_inputs(current_tindex) # **kwargs values

        keys = [current_table.horizontalHeaderItem(i).text() for i in range(headercount)]
        kw = dict(zip(keys, kwargs_arguments))

        args_arguments = [current_table.item(current_table.currentRow(),i).text() for i in range(headercount)]

        Hostel_backend.update(current_tname, *args_arguments, **kw)
        









        





if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_Form()
    ex.show()
    sys.exit(app.exec_())


#def sample_func(self):
    #self.view_btn.clicked.connect(self.backend_function_for_view)
    
